### ISSUE TITLE
texei:package:dependencies:install command requires DevHub 

### ISSUE THREAD

**Issue by ImJohnMDaniel** [texei/texei-sfdx-plugin#57] opened 2021-04-01 16:18 UTC
I noticed that the `texei:package:dependencies:install` command requires the DevHub to be specified.  Is that really required? 

@FabienTaillon, in my version of the command, it was simply because [line 41 was set to true](https://github.com/texei/texei-sfdx-plugin/blob/master/src/commands/texei/package/dependencies/install.ts#L41).  Once I changed that to false, the command worked fine.  I am not aware of a need in the Texei version to have access to the DevHub so I wanted to check with you first.

The use case where this becomes an issue is with customer admin teams trying to just deploy packages in bulk but they don't use a DevHub themselves.  

Let me know if you have questions.

Cheers!

**Comment by FabienTaillon** [comment] 2021-04-02 07:32
Thanks I'll have a look, but I don't think it's needed. Could be one of these 2 reasons:
- It was one of my first command, so at the time I may just have kept the default values for a generated command
- Salesforce install command used under the hood may have required a DevHub at some time, I know some commands have the same kind of issues and have been fixed since then

I'll make sure it's not needed and removed it, thanks for the feedback !

**Comment by FabienTaillon** [comment] 2021-04-23 08:18
@ImJohnMDaniel looks like the DevHub is used [here](https://github.com/texei/texei-sfdx-plugin/blob/master/src/commands/texei/package/dependencies/install.ts#L277).

I think it's in the case where you define your dependency with a Package Id and a Version Number, instead of a Package Version Id. It then need to query the DevHub to retrieve the corresponding 04t Id.

So if it's you use this:
```
"dependencies": [ 
   {
      "package": "MyPackageName",
      "versionNumber": "0.1.0.LATEST"
   }
]
```

instead of this:
```
"dependencies": [ 
   {
      "package": "MyPackageName@0.1.0.1"
   }
]
```

I guess we may mostly be using the 2nd notation now as it's easier with aliases, so it could be something from pre-aliases time.
Still if you use the keys `package` and `versionNumber` (still supported as described [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_unlocked_pkg_config_file.htm)).

What could be done though is to remove the requirement, and display an error message only in the case of a dependency found with `package` and `versionNumber` if no DevHub is set.

Do you think it's worth it ?

**Comment by ImJohnMDaniel** [comment] 2021-04-24 21:06
Hey @FabienTaillon -- apologies for not circling back with you here, but that is exactly what I remembered.  In the end, I did not make the parameter a requirement because it is only relevant if you have a non-pinned dependency setup.  I would recommend making the parameter optional with an error message should it be discovered that one of the dependencies in the `sfdx-project.json` is non-pinned.  Thanks for the help!

**Comment by FabienTaillon** [comment] 2021-04-25 07:25
Makes sense, I'll flag this as an enhancement. Thanks for the suggestion.

**Comment by arafesthain** [comment] 2023-09-28 08:25
Hello @FabienTaillon 
Just got this error since few days : "No default dev hub found. Use -v or --target-dev-hub to specify an environment"

My problem is that I don't want to specify a dev-hub, I just want package installation and nothing more. Any tips to get rid of this ? (more over our Unlock packages have a lot of Different Dev Hubs so define "One" is not an option for us)

**Comment by FabienTaillon** [comment] 2023-09-28 08:58
This is weird because Dev Hub was already [required before](https://github.com/texei/texei-sfdx-plugin/blob/18f49bd748b0ba3ace26ca1244d8dbaa5718bc3b/src/commands/texei/package/dependencies/install.ts#L41C50-L41C50).

What changed since a few days is our migration to sf V2, that moves --targetdevhubusername to --target-dev-hub flag, but both should still work.

Do you have the whole command you're running please ?

**Comment by arafesthain** [comment] 2023-09-28 09:00
`sf texei package dependencies install -a package -r -w 30 --target-org $ORG_ALIAS -k "1: 2: 3: 4: 5: 6: 7: 8: 9: 10: 11: 12: 13:" 2> "$WORKSPACE"/texei_plugin_logs.txt`

**Comment by FabienTaillon** [comment] 2023-09-28 14:28
No you can't. I tried and I couldn't reproduce it, I mean, I'm getting the same behavior before the V2 migration and after.
So without a DevHub I don't know why it was working before.

I could update the code to require it only in a specific scenario, but that will take some time to update. Are you sure you did not have any DevHub de setup previously ?

**Comment by arafesthain** [comment] 2023-09-28 14:57
To be more precise the first error I got (2 days ago Tuesday 26th of September) from the texei CLI is "Error (1): The specified org CI is not a Dev Hub". 
I'm running this exact same pipeline line since 2 years now and never had an error before.
Then from this error I removed in my JWT the set default env hub (as clearly my org was not an env hub the error was fair).
But then I got "No default dev hub found. Use -v or --target-dev-hub to specify an environment"

**Comment by FabienTaillon** [comment] 2023-09-29 08:41
@arafesthain I've removed the Dev Hub as mandatory, and only checking for it when needed, as @ImJohnMDaniel suggested, can you give it a try ?

**Comment by arafesthain** [comment] 2023-09-29 09:02
@FabienTaillon thanks a lot! working perfectly :)
🍾

**Comment by FabienTaillon** [comment] 2023-09-29 09:49
Perfect ! Closing this one then.

**Closed by FabienTaillon** 2023-09-29 09:49 UTC
Labels: enhancement
